### ISSUE TITLE
[BUG] react example does not work with deno 1.7.5

### ISSUE THREAD

**Issue by ivebencrazy** [asos-craigmorten/opine#105]
# Issue

Setup:

- Deno Version: deno 1.7.5
- v8 Version: 9.0.123
- Typescript Version: 4.1.4
- Opine Version: 1.1.0

## Details

[react example](https://github.com/asos-craigmorten/opine/tree/main/examples/react) looks to be broken with latest Deno.

Primarily, this is caused by [breaking change](https://github.com/denoland/deno/discussions/8800) where `Deno.bundle` is deprecated in favor of `Deno.emit`.
Also, I needed to bump dejs (I bumped to `dejs@0.9.3`) to get it working.

I have fix working locally if you'd like me to submit a pr.

Also, was wondering, if this is supposed to be an example, does it make sense to use full opine urls instead of local ref?
ala: `import { opine, serveStatic } from "https://deno.land/x/opine@1.1.0/mod.ts";`
instead of: `import { opine, serveStatic } from "../../mod.ts";`

**Comment by asos-craigmorten** [comment]
Hey @ivebencrazy! 👋 

All sounds very good - we should indeed be using `Deno.emit()` now instead of `Deno.bundle()`!

If you have a fix on the go then a PR would be very welcome! 😄 🎉 

R.E. the examples it's a good point - I guess to be good "lift and shift" / "copy and paste" material for getting started then really we should use the full urls - if that's something you'd be open to putting into / adding to a PR that would be awesome as well 🙂
