### ISSUE TITLE
Not available on nest.land

### ISSUE THREAD

**Issue by waghanza** [asos-craigmorten/opine#120]
Hi,

`opine` `1.3.3` seems not to be available in https://nest.land/package/opine, but available in https://deno.land/x/opine.

Regards,

**Comment by asos-craigmorten** [comment]
Hi @waghanza 👋 

Good spot! Seems I run the full lint, test etc. in the publish workflow. Because ( last time I checked ) the eggs CLI had issues on latest Deno `^1.9.0` I left it the eggs publish workflow on `^1.8.0` but a breaking change ( well been described as a bugfix ) to how `Headers` works in Deno in one of the `^1.9.0` versions now means the Opine tests fail on `^1.8.0`.

I'll update the workflow and 🤞 a `1.3.4` version and future versions will be made available on <https://nest.land>.

**Comment by waghanza** [comment]
You should probably also update current `README`

**Comment by cmorten** [comment]
Will close once the working version is released 🙂

**Comment by cmorten** [comment]
Pleased to say the CI changes worked ( REF: https://github.com/asos-craigmorten/opine/runs/2519010498?check_suite_focus=true ) and `1.3.4` is available on nest.land now 😄 --> https://nest.land/package/opine
