### ISSUE TITLE
Calling req.body.read() in a post or put method crashes deno

### ISSUE THREAD

**Issue by creeperkafasi** [asos-craigmorten/opine#141]
# Calling Request.body.read() in a post or put method crashes deno

Setup:

- Deno Version: 1.13.2 (release, x86_64-unknown-linux-gnu) *(compiled from source with cargo)*
- v8 Version: 9.3.345.11
- Typescript Version: 4.3.5
- Opine Version: @1.7.2

## Details

I have this code and I want to read the contents of a post request body:
```ts
const app = opine();

app
  .use("/public", serveStatic(`${Deno.cwd()}/public`))
  .post("/msg", async (req, res, next) => {
        req.body.read()
    })

app.listen({ port: port, hostname: hostname }, () => { console.log(`http://${hostname}:${port}`) })
```

<details>
<summary>When I send a post request to the server I get this error (click to expand)</summary>

```
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'byteLength')
    if (remaining >= buf.byteLength) {
                         ^
    at Object.read (https://deno.land/std@0.105.0/http/_io.ts:26:26)
    at file:///home/denizt/dev/remodeApp/app.ts:74:18
    at Layer.handle [as handle_request] (https://deno.land/x/opine@1.7.2/src/router/layer.ts:76:11)
    at next (https://deno.land/x/opine@1.7.2/src/router/route.ts:104:13)
    at Route.dispatch (https://deno.land/x/opine@1.7.2/src/router/route.ts:79:3)
    at Layer.handle [as handle_request] (https://deno.land/x/opine@1.7.2/src/router/layer.ts:76:11)
    at https://deno.land/x/opine@1.7.2/src/router/index.ts:267:24
    at Function.process_params (https://deno.land/x/opine@1.7.2/src/router/index.ts:334:12)
    at next (https://deno.land/x/opine@1.7.2/src/router/index.ts:256:10)
    at file:///home/denizt/dev/remodeApp/app.ts:37:19
```

</details>

Removing the .post part from the code fixes the issue so the problem is the post method
Changing `.post` to `.put` doesn't make a difference

(Tried this on both deno 1.13.1 and 1.13.2)

**Comment by cmorten** [comment]
Curious! The error is coming from the std/http lib module which Opine uses, but worth checking that not doing something strange with the body in Opine…

Be curious to know if is reproduceable with just the std/http lib (outside of Opine).

**Comment by cmorten** [comment]
@creeperkafasi sorry took so long to look into this a bit more.

In this instance it is a case of the std lib's buffer read implementation not giving you back a particularly good error message 😅 the `read(p: Uint8Array)` requires you to pass a `Uint8Array` to which the stream can be read into. For example, we can fix up your example as follows:

```ts
import { opine, serveStatic } from "./mod.ts";

const port = 3000;
const hostname = "127.0.0.1";

const app = opine();

app
  .use("/public", serveStatic(`${Deno.cwd()}/public`))
  .post("/msg", async (req, res, _next) => {
    // Determine the size of the message and therefore how big a buffer we need.
    const contentLength = parseInt(req.headers.get("content-length") ?? "0");
    const buffer = new Uint8Array(contentLength);

    // Read the request body into our buffer
    await req.body.read(buffer);

    // Do something with that buffer - here we just respond with it to the POST request.
    res.send(buffer);
  });

app.listen({ port, hostname }, () => {
  console.log(`http://${hostname}:${port}`);
});
```

If you want to look into the method a bit more, check out [he potential return types of the request body provided by the legacy http std lib module (REF: https://deno.land/std@0.107.0/http/server_legacy.ts#L91), and the core Deno docs on the `Deno.Reader` interface which the http body satisifies (REF: https://doc.deno.land/builtin/stable#Deno.Reader).

I would also check out the Opine docs on `req.body` (REF: https://github.com/asos-craigmorten/opine/blob/main/.github/API/request.md#reqbody) including some of the body parsing middleware that Opine provides, namely:

- [`json()`](https://github.com/asos-craigmorten/opine/blob/main/.github/API/middlewares.md#jsonoptions)
- [`raw()`](https://github.com/asos-craigmorten/opine/blob/main/.github/API/middlewares.md#rawoptions)
- [`text()`](https://github.com/asos-craigmorten/opine/blob/main/.github/API/middlewares.md#textoptions)
- [`urlencoded()`](https://github.com/asos-craigmorten/opine/blob/main/.github/API/middlewares.md#urlencodedoptions)

These can likely save you some time writing bespoke code for parsing and consuming the request body 😄 

---

As this is an error with using the `read()` method rather than a bug with Opine, I'm going to close - please reopen if disagree!
