### ISSUE TITLE
Bug on deno std, or opine ???

### ISSUE THREAD

**Issue by waghanza** [asos-craigmorten/opine#147]
Hi @asos-craigmorten,

Trying to add `opine` to https://github.com/the-benchmarker/web-frameworks. I am facing the following error
```javascript
error: TS2339 [ERROR]: Property 'getIterator' does not exist on type 'ReadableStream<R>'.
  return res.readable.getIterator();
                      ~~~~~~~~~~~
    at https://deno.land/std@0.69.0/async/pool.ts:45:23
```

Setup:

- Deno Version: `1.16.1` (**alpine**)
- v8 Version: `9.7.106.2`
- Typescript Version:  `4.4.2`
- Opine Version: `1.9.0`

Source code:

```javascript
import { opine } from "https://deno.land/x/opine@1.9.0/mod.ts";

const app = opine();

app.get("/", function (_, res) {
  res.send("");
});

app.get("/user/:id", (req, res) => {
    res.end(req.params.id);
})

app.post("/user", (_, res) => {
    res.end("");
})

app.listen("0.0.0.0:3000");
```

Regards,

**Comment by yacinehmito** [comment]
I've just been hit by the same issue.

**Comment by cmorten** [comment]
Hey folks 👋 

Thanks for flagging this - hopefully https://deno.land/x/opine@1.9.1 resolves the issue. Please reopen if otherwise!

I suspect [Opine will benchmark fairly low on that list](https://github.com/asos-craigmorten/opine/pull/148#issuecomment-968357835) 😅 contrary to efforts on the Deno std lib, with Opine the focus was always feature support over performance... perhaps should try to remedy that 🤔 awesome to hear that you're trying to get Deno projects onto that list though! 🚀

**Comment by saipasha** [comment]
Thank you for the fast action. I just ran into the same issue.

**Comment by yacinehmito** [comment]
Thank you very much.
