### ISSUE TITLE
bug: Response.location doesn't exist

### ISSUE THREAD

**Issue by marc2332** [asos-craigmorten/opine#3]
# Issue
Response object doesn't have the location property, neither redirect.

## Details

Technically, there is a location property on Response object as said here: https://github.com/asos-craigmorten/opine/blob/master/.github/API/response.md#reslocationpath

But there isn't, here a simple example:

I would like the route "/redirect" to redirect to "/home":
```javascript
app.get('/redirect',(req,res,next)=>{
	res.location("/home") //location doesn't exist
})
```
I don't know if I am doing anything wrong or it's really a bug.

Thanks 😄

**Comment by asos-craigmorten** [comment]
Hi @marc2332 I'll take a look at that now - it is most likely a bug 😂

**Comment by asos-craigmorten** [comment]
Ah! @marc2332 so there is a small bug in the type definitions which is why your IDE is likely complaining that location does not exist (I had forgotten to uncomment since implementing the method!)

As to why (even if you wrote something like `(res as any).location("/home")`) this isn't redirecting, it is because `res.location()` just sets a `Location` header as per the [Opine docs](https://github.com/asos-craigmorten/opine/blob/master/.github/API/response.md#reslocationpath).

If you want to perform a redirect, you need to send a response yourself (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location), specifically a status code of `201` or `3xx` depending on the reason for redirecting.

I am updating the types now and will add an example for using the `res.location()` method which will look something like:

```ts
const app = opine();

app.get("/home", function (req, res, next) {
  res.send("Hello Deno!");
});

app.get("/redirect", function (req, res, next) {
  res.location("/home").sendStatus(301);
});

app.listen(3000);
console.log("Opine started on port 3000");
console.log("Try opening http://localhost:3000/redirect");
```

I intend to implement the equivalent of the `res.redirect()` that [Express has](https://expressjs.com/en/4x/api.html#res.redirect) very soon.

**Comment by marc2332** [comment]
I haven't explained my self very well... 😅 It's not a type error, it literally doesn't exist:

![imagen](https://user-images.githubusercontent.com/38158676/83048062-65d90680-a049-11ea-8c92-6fb842730c8e.png)

**Comment by marc2332** [comment]
Thanks ! it worked! 

```javascript
app.get('/redirect',(req,res)=>{
	(res as any).location("/home").sendStatus(301);
})
```

**Comment by asos-craigmorten** [comment]
Done. Please refer to the updated API documentation and the location example --> https://github.com/asos-craigmorten/opine/tree/master/examples/location

**Comment by asos-craigmorten** [comment]
> Thanks ! it worked!
> 
> ```js
> app.get('/redirect',(req,res)=>{
> 	(res as any).location("/home").sendStatus(301);
> })
> ```

Release in version `0.5.1`.
