### ISSUE TITLE
Can't assign new properties to "req"

### ISSUE THREAD

**Issue by abbasogaji** [asos-craigmorten/opine#45]
# Issue
Can't assign new properties to "req"
Setup:

- Deno Version:  1.0.0
- v8 Version: v8 8.4.300
- Typescript Version: 3.9.2
- Opine Version: 0.19.1

## Details

> Please replace this quote block with the details of the feature / bug you wish to be addressed. If it is a bug please do your best to add steps to reproduce.

**Comment by asos-craigmorten** [comment]
Hi @abbasogaji can you provide some more details about where you are seeing this error + a minimal reproduceable example?

This looks likely to be a type error because the Opine `Request` type on the `req` object doesn’t allow arbitrary properties - if you wish to extend the object with your own properties then I would expect that you define your own type that extends the Opine `Request` type. Alternatively if you are not interested in using types you can use Opine in pure JavaScript files.

If you are looking to store properties and pass them between middleware, the recommended way is to use the `res.locals` object. Please see the docs —> https://github.com/asos-craigmorten/opine/blob/main/.github/API/response.md#reslocals
