### ISSUE TITLE
Question: Shall I publish this module via https://nest.land/

### ISSUE THREAD

**Issue by michael-spengler** [asos-craigmorten/opine#64]
Background: I like it very much + I like the concept of https://nest.land/

I'm already relying in some production contexts on opine :) 👍

**Comment by asos-craigmorten** [comment]
Hi @michael-spengler glad you’re enjoying it!

Not sure I quite understand what this issue is for? (Maybe need to wake up and have more coffee! ☕️)

Opine is already published to nest.land (see https://nest.land/package/opine), and there are instructions on the readme how to install from that registry. 😊

If you’re talking about your own module then by all means publish it! The more that’s out there, the more it benefits the Deno community as a whole! 😄

If I’ve misunderstood please elaborate! Otherwise will close this issue in a little while.

**Comment by michael-spengler** [comment]
:) great - I had not found it earlier - perhaps a typo came in the middle of https://nest.land/package/opine and me. 

So it seems to be me who needs more coffee :) - enjoy and keep up the good work.
